[package]
name = "esphome-core"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-sync = "0.7.2"
embassy-executor = { version = "0.9.1", features = ["executor-thread"] }
embassy-time = { version = "0.5.0", features = ["generic-queue-8"] }
async-trait = "0.1"
log = "0.4"
heapless = "0.8"
serde = { version = "1.0", default-features = false }
